[package]
name = "quest2"
version = "0.1.0"
authors = ["Dia <naadia@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
